
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 17;
  public static final int PUNTOYCOMA = 27;
  public static final int DOSPUNTOS = 26;
  public static final int DECIMAL = 30;
  public static final int DIVIDIDO = 19;
  public static final int PALABRA = 31;
  public static final int ETIQUETAS = 7;
  public static final int EJECUTAR = 13;
  public static final int POR = 18;
  public static final int TIPO = 10;
  public static final int PORCENTAJE = 15;
  public static final int BARRAS = 3;
  public static final int VALORES = 8;
  public static final int COMA = 25;
  public static final int EOF = 0;
  public static final int TOTAL = 11;
  public static final int DEF = 2;
  public static final int PIE = 33;
  public static final int COMILLA = 24;
  public static final int EXTRA = 12;
  public static final int CANTIDAD = 14;
  public static final int PARENTESIS_C = 21;
  public static final int error = 1;
  public static final int LLAVE_C = 29;
  public static final int PARENTESIS_A = 20;
  public static final int LLAVE_A = 28;
  public static final int EJEY = 6;
  public static final int EJEX = 5;
  public static final int ENTERO = 32;
  public static final int CORCHETE_C = 23;
  public static final int CORCHETE_A = 22;
  public static final int UNIR = 9;
  public static final int TITULO = 4;
  public static final int MAS = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DEF",
  "BARRAS",
  "TITULO",
  "EJEX",
  "EJEY",
  "ETIQUETAS",
  "VALORES",
  "UNIR",
  "TIPO",
  "TOTAL",
  "EXTRA",
  "EJECUTAR",
  "CANTIDAD",
  "PORCENTAJE",
  "MAS",
  "MENOS",
  "POR",
  "DIVIDIDO",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "CORCHETE_A",
  "CORCHETE_C",
  "COMILLA",
  "COMA",
  "DOSPUNTOS",
  "PUNTOYCOMA",
  "LLAVE_A",
  "LLAVE_C",
  "DECIMAL",
  "PALABRA",
  "ENTERO",
  "PIE"
  };
}

